name: Auto Update Skills

on:
  schedule:
    - cron: "0 0 * * *" # tiap hari
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Script
        run: node .github/scripts/skill.js

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "auto update skills" || echo "no changes"
          git push
